services:
    caddy:
        container_name: caddy
        image: docker.zachklingbeil.com/caddy
        volumes:
            - caddy:/data/caddy
            - ./Caddyfile:/etc/caddy/Caddyfile
        networks:
            - timefactory
        ports:
            - 443:443
            - 443:443/udp
        environment:
            - CF_API_TOKEN=${CF_API_TOKEN}
        restart: always

    redis:
        image: redis/redis-stack-server
        container_name: redis
        # expose:
        #     - 6379
        ports:
            - 6379:6379
        volumes:
            - redis:/data
        environment:
            - REDIS_USER=zk
            - REDIS_PASSWORD=${PASSWORD}
            - REDIS_PORT=6379
            - REDIS_BIND=0.0.0.0
            - REDIS_ARGS=--maxmemory 24GB --maxmemory-policy allkeys-lru
        networks:
            - timefactory
        restart: unless-stopped
        pull_policy: always

    registry:
        container_name: registry
        image: registry
        expose:
            - 5000
        volumes:
            - registry:/registry
            - ./auth/:/auth
        networks:
            - timefactory
        environment:
            REGISTRY_AUTH: htpasswd
            REGISTRY_AUTH_HTPASSWD_REALM: Registry Realm
            REGISTRY_AUTH_HTPASSWD_PATH: /auth/htpasswd
            REGISTRY_STORAGE_FILESYSTEM_ROOTDIRECTORY: /registry
            REGISTRY_HTTP_SECRET: ${PASSWORD}
            REGISTRY_TRACING_ENABLED: false
        restart: always
        pull_policy: always

networks:
    timefactory:
        external: true

volumes:
    caddy:
        external: true
    redis:
        external: true
    registry:
        external: true
