services:
    lab:
        image: gitlab/gitlab-ce
        container_name: lab
        restart: always
        expose:
            - 80
        volumes:
            - lab:/etc/gitlab
        shm_size: '1g'
        networks:
            - timefactory
networks:
    timefactory:
        external: true
volumes:
    lab:
        external: true
