name: Dev Release Workflow

on:
    push:
        branches:
            - main # Trigger on commits to the main branch

jobs:
    dev-release:
        runs-on: self-hosted
        name: Create Dev Release
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20 # Specify the Go version

            - name: Build the Package
              run: |
                  go build ./...

            - name: Run Tests
              run: |
                  go test ./...

            - name: Create Dev Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  TAG_NAME="dev-$(date +'%Y%m%d%H%M%S')"
                  echo "Creating dev release with tag $TAG_NAME"
                  gh release create "$TAG_NAME" --notes "Dev release for commit $GITHUB_SHA" --prerelease
