name: Stable Release Workflow

on:
    push:
        branches:
            - main # Trigger on commits to the main branch

jobs:
    stable-release:
        if: contains(github.event.head_commit.message, '[stable-release]')
        runs-on: self-hosted
        name: Create Stable Release
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

            - name: Set up Go
              uses: actions/setup-go@v4
              with:
                  go-version: 1.20 # Specify the Go version

            - name: Build the Package
              run: |
                  go build ./...

            - name: Run Tests
              run: |
                  go test ./...

            - name: Create Stable Release
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              run: |
                  TAG_NAME="v$(date +'%Y.%m.%d')"
                  echo "Creating stable release with tag $TAG_NAME"
                  gh release create "$TAG_NAME" --notes "Stable release for commit $GITHUB_SHA"
